ALLUSERSPROFILE=C:\ProgramData
AMPLITUDE_API_KEY=28f3cae0b33b8b3702120c9ed1a935aa
AMPLITUDE_API_KEY_GREENBUCKET_DEV=3ded2a762163603391a425f688f990c8
AMPLITUDE_API_KEY_GREENBUCKET_PROD=c86fea37a9e1d3f0878b96e15b111c7c
AMPLITUDE_API_KEY_REDBUCKET_DEV=46b8b46515e7632fc42a504b72e05fd0
AMPLITUDE_API_KEY_REDBUCKET_PROD=ca12bb461ea96f9bdf5df4ded7d52994
AMPLITUDE_API_KEY_STAGING=83ee04fccc67e4fcc7dd527c4c6f1e21
AMPLITUDE_API_KEY_YELLOWBUCKET_DEV=48835b4d1f5e342aefe5f016324d296a
AMPLITUDE_API_KEY_YELLOWBUCKET_PROD=e03a9bbe92dc38a88cdb068d24c65b46
AMPLITUDE_DEPLOYMENT_KEY_RED_BUCKET_DEV=client-wbjHYrmeSR87GmWOE7LDpf7sUySOIKHm
AMPLITUDE_DEPLOYMENT_KEY_RED_BUCKET_PROD=client-zH8Y7OK1i331EKuG77C6UxN8ygcM6LzS
AMPLITUDE_TOKEN_GREENBUCKET_DEV=84H2gMm_FJzhr3mBaX1lM1JVukmCM7d9
AMPLITUDE_TOKEN_GREENBUCKET_PROD=ZpUcbAdZXJYzNSoHsAWtL_s_JppwWid9
AMPLITUDE_TOKEN_REDBUCKET_DEV=U4PSN7S7PuYVRODivvdcFwbu8R6IHGqa
AMPLITUDE_TOKEN_REDBUCKET_PROD=jTIgKs5KTZOjiqEEVdZFbgo_VRhABduL
AMPLITUDE_TOKEN_YELLOWBUCKET_DEV=wKi8foVigDditGFvmZewRFWsEbX9Y0YO
AMPLITUDE_TOKEN_YELLOWBUCKET_PROD=UYDQtPOw83dIfVy3SrW5oMyo7ru4PRkV
APPDATA=C:\Users\Leandro Ishida\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_8692_CXHFNCZMRMGZVGWS
COMMANDPROMPTTYPE=Native
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPLUS_FUSIONENABLEFORCEDFULLCLOSUREWALK=1
COMPLUS_THREADPOOL_USEPORTABLETHREADPOOL=0
COMPUTERNAME=LINKCCA
COMSPEC=C:\WINDOWS\system32\cmd.exe
C_EM64T_REDIST11=C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\
DEBUG_ENV_VAR=UnityHub
DEVENVDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\
DOTNET_MULTILEVEL_LOOKUP=0
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
EFC_29712=1
EXTENSIONSDKDIR=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
EXTERNAL_INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
FRAMEWORK40VERSION=v4.0
FRAMEWORKDIR=C:\Windows\Microsoft.NET\Framework\
FRAMEWORKDIR32=C:\Windows\Microsoft.NET\Framework\
FRAMEWORKVERSION=v4.0.30319
FRAMEWORKVERSION32=v4.0.30319
FSHARPINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools
GCEXPCONFIGUSEDINSESSION=3
HOMEDRIVE=C:
HOMEPATH=\Users\Leandro Ishida
IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAbYksmLPc50C2+GImYox03AQAAAACAAAAAAAQZgAAAAEAACAAAAARgup/caLB3/0WAonyikqxf42Fv5Pj+xmDsBM69tmFoAAAAAAOgAAAAAIAACAAAADZfSAXFaiExXCD6fRPn10Ex+bXV3mHCXfCgDgriZfLLmAAAACCyIL487yIlfaFSuxMW8ywr9OiF2i2Sf0VVRuDY3opRldSk5EMk0MTCpLzaNEfs37QZV9p1UzX0vK2lf2TBHN6cpI5GxrY84B28WD1EErerKOwuK8bXLaDXZVKav/ymEZAAAAAN8iqdG754XgaMsDFESBydtqzbvC4RmMfqUlxOmSpPuRMRXm5rW8jlXyLko2qI5oOaaERyruimRqGQnm4mVfUHw==
INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x86
LIBPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework\v4.0.30319
LOCALAPPDATA=C:\Users\Leandro Ishida\AppData\Local
LOGONSERVER=\\LINKCCA
MSBUILDLOADMICROSOFTTARGETSREADONLY=true
NETFXSDKDIR=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\
NUMBER_OF_PROCESSORS=8
NVIDIAWHITELISTED=0x01
ONEDRIVE=C:\Users\Leandro Ishida\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX86\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\DiagnosticsHub\Collector;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x86;C:\Program Files (x86)\Windows Kits\10\bin\\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files\Python313\Scripts\;C:\Program Files\Python313\;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Rockwell Software\RSCommon;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Rockwell;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\sinapse\AppData\Roaming\Python\Python312\Scripts\;C:\Users\Evelyn Paz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts;C:\Program Files\MySQL\MySQL Server 9.0\bin;C:\Users\Leandro Ishida\AppData\Local\Programs\Python\Launcher\;C:\Users\Leandro Ishida\AppData\Local\Microsoft\WindowsApps;C:\Users\Leandro Ishida\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.12;C:\Users\Leandro Ishida\.dotnet\tools;D:\Microsoft VS Code\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
PKGDEFAPPLICATIONCONFIGFILE=C:\Users\Leandro Ishida\AppData\Local\Microsoft\VisualStudio\17.0_bd78626b\devenv.exe.config
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 140 Stepping 2, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8c02
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Users\Leandro Ishida\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SENTRY_ACCESS_TOKEN=3df78d9e53f8456aa90fbae044ce1a6261421ab1d0014674bc2e933477289017
SERVICEHUBCLIENTPROCESSVERSION=17.10.35122.118 built by: d17.10
SERVICEHUBCURRENTOSLOCALE=pt-BR
SERVICEHUBLOCATIONSERVICEPIPENAME=16275c9c6009954f8731e91c155f778acc5ee3b7bba364f2905dcfece1a1aaa9
SERVICEHUBLOGSESSIONKEY=61B2364D
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\Leandro Ishida\AppData\Local\Temp
THREADEDWAITDIALOGDPICONTEXT=-4
TMP=C:\Users\Leandro Ishida\AppData\Local\Temp
UCRTVERSION=10.0.22621.0
UNIVERSALCRTSDKDIR=C:\Program Files (x86)\Windows Kits\10\
USERDOMAIN=LINKCCA
USERDOMAIN_ROAMINGPROFILE=LINKCCA
USERNAME=Leandro Ishida
USERPROFILE=C:\Users\Leandro Ishida
VCIDEINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\
VCPKG_ROOT=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg
VCTOOLSINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\
VCTOOLSREDISTDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.40.33807\
VCTOOLSVERSION=14.40.33807
VISUALSTUDIODIR=C:\Users\Leandro Ishida\Documents\Visual Studio 2022
VISUALSTUDIOEDITION=Microsoft Visual Studio Community 2022
VISUALSTUDIOVERSION=17.0
VS170COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\
VSAPPIDDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\
VSAPPIDNAME=devenv.exe
VSCMD_ARG_APP_PLAT=Desktop
VSCMD_ARG_HOST_ARCH=x86
VSCMD_ARG_TGT_ARCH=x86
VSCMD_VER=17.10.5
VSINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\
VSLANG=1046
VSPERMONITORDPIAWARENESSENABLED.35228=TRUE
VSSKUEDITION=Community
VS_PERF_SESSION_GCHEAPCOUNT=2
WINDIR=C:\WINDOWS
WINDOWSLIBPATH=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0
WINDOWSSDKBINPATH=C:\Program Files (x86)\Windows Kits\10\bin\
WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10\
WINDOWSSDKLIBVERSION=10.0.22621.0\
WINDOWSSDKVERBINPATH=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\
WINDOWSSDKVERSION=10.0.22621.0\
WINDOWSSDK_EXECUTABLEPATH_X64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\
WINDOWSSDK_EXECUTABLEPATH_X86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
WOOTRIC_CLIENT_TOKEN=NPS-aa8be4c3
ZES_ENABLE_SYSMAN=1
__DOTNET_ADD_32BIT=1
__DOTNET_PREFERRED_BITNESS=32
__VSCMD_PREINIT_PATH=C:\Program Files\Python313\Scripts\;C:\Program Files\Python313\;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Rockwell Software\RSCommon;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Rockwell;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\sinapse\AppData\Roaming\Python\Python312\Scripts\;C:\Users\Evelyn Paz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts;C:\Program Files\MySQL\MySQL Server 9.0\bin;C:\Users\Leandro Ishida\AppData\Local\Programs\Python\Launcher\;C:\Users\Leandro Ishida\AppData\Local\Microsoft\WindowsApps;C:\Users\Leandro Ishida\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.12;C:\Users\Leandro Ishida\.dotnet\tools;D:\Microsoft VS Code\bin
